name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node version
        id: retrieve-node-version
        run: |
          NODE_NVMRC=$(cat .nvmrc)
          NODE_VERSION=${NODE_NVMRC/v/''}
          echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: ${{ steps.retrieve-node-version.outputs.node_version }}

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:unit --coverage

      - name: Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Unit Test Results
          path: "junit.xml"
          reporter: jest-junit
          fail-on-error: true

  integration:
    name: Integration test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node version
        id: retrieve-node-version
        run: |
          NODE_NVMRC=$(cat .nvmrc)
          NODE_VERSION=${NODE_NVMRC/v/''}
          echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: ${{ steps.retrieve-node-version.outputs.node_version }}

      - name: Install
        run: npm ci

      - name: Playwright
        run: npx playwright install --with-deps

      - name: Environment
        run: echo "TBA_API_KEY=${{ secrets.TBA_API_KEY }}" >> .env

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:integration

      - name: Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Integration Test Results
          path: "junit.xml"
          reporter: jest-junit
          fail-on-error: true
