name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install
        run: npm install

      - name: Unit tests
        run: npm run test:unit --coverage

      - name: Integration tests
        run: |
          TBA_API_KEY: ${{ secrets.TBA_API_KEY }} npm run test:integration

      - name: Report
        uses: dorny/test-reporter@v2
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && !cancelled() }}
        with:
          name: Test Results
          path: "junit.xml"
          reporter: jest-junit
          fail-on-error: true
